### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ilu33** [douzepouze/space-inventory#14]
pip install -r requirements.txt fails with
```py
Command /home/.../.virtualenvs/p27-inv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-G_2bBf/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_qiS3E-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/.../.virtualenvs/p27-inv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-G_2bBf/Pillow
Exception information:
Traceback (most recent call last):
  File "/home/.../.virtualenvs/p27-inv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/.../.virtualenvs/p27-inv/local/lib/python2.7/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/.../.virtualenvs/p27-inv/local/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/.../.virtualenvs/p27-inv/local/lib/python2.7/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/.../.virtualenvs/p27-inv/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /home/.../.virtualenvs/p27-inv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-G_2bBf/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_qiS3E-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/.../.virtualenvs/p27-inv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-G_2bBf/Pillow
```

**Comment by wklaebe** [comment]
Sounds like https://github.com/python-pillow/Pillow/issues/1457 - install libjpeg-dev and try again.

Against the build errors coming up afterwards I needed more packages:
zlib1g-dev build-essential python-dev
